// @flow

export const SET_PLAYBACK = 'SET_PLAYBACK';
export const SET_PLACE_NEW_TAG_MODE = 'SET_PLACE_NEW_TAG_MODE';
export const SET_CURRENT_TIME = 'SET_CURRENT_TIME';
export const SET_DURATION = 'SET_DURATION';
